### ISSUE TITLE
Add an informative tooltip on each entries in the Tracker list

### ISSUE THREAD

**Issue by mokachokokarbon** [mokachokokarbon/Betty#2]
The informative tooltip should show the following details:

**Filing Dialog**
- [x] the whole template (or just a preview)
- [x] type of template
- [x] date/time<sup>1</sup>

**Searching Dialog**
- [x] the whole template (or just a preview)
- [x] type of template
- [x] number of days
- [x] importance
- [x] date/time<sup>1</sup>

<sup>1</sup> _The tooltip should show the actual date/time created, not the value of the item in the Tracker list._
